license = "AllRightsReserved"
issueTrackerURL = "https://github.com/ApexModder/BetterSnow/issues"
modLoader = "javafml"
loaderVersion = "[2,)"

[[mods]]
    modId = "${MOD_ID}"
    displayName = "${MOD_NAME}"
    version = "${MOD_VERSION}"
    displayURL = "https://github.com/ApexModder/BetterSnow"
    # updateJSONURL = "https://api.modrinth.com/updates/${MOD_ID}/forge_updates.json"
    credits = "ApexStudios"
    logoFile = "banner.png"
    description = "Replaces Vanilla Snow FX with the 'WHITE_ASH' particle"
    authors = "Apex"

    [["dependencies.${MOD_ID}"]]
        modId = "minecraft"
        versionRange = "[1.20.4,1.20.5)"
        type = "required"
        ordering = "NONE"
        side = "BOTH"
    [["dependencies.${MOD_ID}"]]
        modId = "neoforge"
        versionRange = "[20.4,20.5)"
        type = "required"
        ordering = "NONE"
        side = "BOTH"