on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1000
                  fetch-tags: true

            - name: Make Gradle executable
              run: chmod +x ./gradlew

            - name: Setup Java 17
              uses: actions/setup-java@v4.1.0
              with:
                  java-version: 17
                  distribution: 'adopt'

            - name: Publish with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                arguments: publish
                cache-read-only: false
              env:
                MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}